### ISSUE TITLE
CURA and serviceWorker

### ISSUE THREAD

**Issue by VegtMedia-Alex** [frontarm/create-universal-react-app#3]
When I use the default service worker with CURA i get this errors:

bad-precaching-response

I am registering the serviceWorker inside the function main from the index.js, is CURA tested with serviceworkers?

**Comment by jamesknelson** [comment]
I run the simple and kitchensink test suites, but not sure if they include service workers. If service workers aren't working, I assume that they don't.

Would happily merge a fix if you can get them working.

**Comment by VegtMedia-Alex** [comment]
I think its in the core of CURA since CRA does also not allow to edit the serviceWorker properties.

After a little digging I got a more describing error:

```
WorkboxError.mjs:33 Uncaught incorrect-type: The parameter 'cachedAssetUrl' passed into 'workbox-routing.registerNavigationRoute()' must be of type string.
    at Object.isType (https://storage.googleapis.com/workbox-cdn/releases/4.3.1/workbox-core.dev.js:457:13)
    at Object.registerNavigationRoute (https://storage.googleapis.com/workbox-cdn/releases/4.3.1/workbox-routing.dev.js:814:25)
    at http://localhost:3001/service-worker.js:36:17
```

Is CURA doing anything with this variable "cachedAssetUrl"?

**Comment by jamesknelson** [comment]
afaik workbox is a plugin that's added to the webpack config, so if there's an issue, I imagine it's in the config.

https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/config/webpack.config.js

It might be worth ejecting in a temporary branch and seeing if you can get it working by playing with the webpack config there. If you can, it should be a relatively easy fix to merge in on this side.

**Comment by VegtMedia-Alex** [comment]
I dont have that much knowledge about CRA yet.

But if you are not changing the cachedAssetUrl in CURA then I guess this error would also occur in CRA but there it is working as expected.

That's strange right?

**Comment by jamesknelson** [comment]
From that error, I think cachedAssetURL is generated by the workbox webpack plugin -- it's not something that CURA or CRA has access to directly. If it's not there, it probably indicates that either:

1. The Workbox plugin doesn't support multicompilers (a Webpack feature used by CURA, but *not* used by vanilla CRA), or
2. The Workbox plugin's configuration is incorrect in CURA. This is a possibility, as a number of Webpack features need to be configured differently in CURA vs. vanilla CRA.

It feels kind of odd to me that this is occurring at all though... I would have thought that service workers are tested in the CRA test suite. 🤷‍♂️

**Comment by VegtMedia-Alex** [comment]
```
PrecacheController.mjs:194 Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"https://www.domain.com/node/index.html?__WB_REVISION__=066dd6f296be39af04e5b0c34a4e4e2c","status":404}]
    at l.o (https://storage.googleapis.com/workbox-cdn/releases/4.3.1/workbox-precaching.prod.js:1:1749)
    at async Promise.all (index 0)
    at async l.install (https://storage.googleapis.com/workbox-cdn/releases/4.3.1/workbox-precaching.prod.js:1:1221)
```
It is not caching them because all assets have a 404 like:

https://www.domain.com/node/index.html?__WB_REVISION__=066dd6f296be39af04e5b0c34a4e4e2c

Are this urls correct? with /node/ inbetween?

**Comment by jamesknelson** [comment]
With CURA, it outputs two versions of the build:

- build/node (which contains the commonjs version, which can be used for SSR)
- build/web (which contains the web version, identical to what CRA produces)

It sounds like you'll need to somehow tell it ignore the build/node version, and just use the build/web version.

**Comment by VegtMedia-Alex** [comment]
I thought so too, but there is no index.html in the web folder?

Or should it be:

https://www.domain.com/?__WB_REVISION__=066dd6f296be39af04e5b0c34a4e4e2c

**Comment by jamesknelson** [comment]
Ah right... yeah, index.html is not there, as pages are rendered using SSR instead of with the static index.html.

I wonder if you need to add this to the `exclude` line in webpack.config.js?

https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/config/webpack.config.js#L672

**Comment by VegtMedia-Alex** [comment]
I am not on an ejected CRA, or is this not needed? If you can prepare a CURA beta on another branch i can test it easily by adjusting the version in package.json to branchname right?

**Comment by jamesknelson** [comment]
Preparing a CURA beta takes 30 min ~ 1 hour -- it's a pretty heavy process. If you can eject on another branch and find a fix, it'll help a ton.

**Comment by VegtMedia-Alex** [comment]
I would love too but I really don't know how :(

**Comment by VegtMedia-Alex** [comment]
I just followed a guide an now i see the config/webpack.config.js

But the line you just highlighted:

```
exclude: [/\.map$/, /asset-manifest\.json$/],
```
Is already there?

**Comment by jamesknelson** [comment]
Nice job 👍  Yep, that line should be there -- can you please try to:

- add `, /index\.html$/` at the end of that line
- removing the `navigateFallback` and `navigateFallbackBlacklist` options

```js
new WorkboxWebpackPlugin.GenerateSW({
          clientsClaim: true,
          exclude: [/\.map$/, /asset-manifest\.json$/, /index\.html$/],
          importWorkboxFrom: 'cdn',
        }),
```

Then see if that works

**Comment by VegtMedia-Alex** [comment]
Very nice job! When i make it like your example its all working!

Will you change this in CURA? And on which time frame? :)

Thanks a lot!!

<img width="674" alt="Screenshot 2019-10-01 at 13 57 48" src="https://user-images.githubusercontent.com/3672692/65959914-7baf1100-e453-11e9-8049-4892f18e1302.png">

**Comment by jamesknelson** [comment]
Thanks! I definitely want to fix this in CURA. Will aim to get it done over the weekend -- ping me if I haven't managed it by Monday next week.

**Comment by VegtMedia-Alex** [comment]
Will do for sure ;)

**Comment by VegtMedia-Alex** [comment]
Just a friendly reminder, so you won't forget it this weekend ;)

**Comment by jamesknelson** [comment]
Just published this as part of CURA 3.2.0. Thanks for the help!

**Comment by VegtMedia-Alex** [comment]
Awesome!

**Comment by VegtMedia-Alex** [comment]
@jamesknelson Is this something we can fix in the serviceworker declaration?

See attached:
<img width="736" alt="Screenshot 2019-10-09 at 20 21 57" src="https://user-images.githubusercontent.com/3672692/66509053-90824900-ead2-11e9-964c-a30612d02c83.png">
